# Generated by Django 3.1.3 on 2020-11-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('short_name', models.CharField(max_length=10, null=True)),
                ('logo', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('short_name', models.CharField(max_length=10, null=True)),
                ('logo', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('faculta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=10, null=True)),
                ('phone2', models.CharField(max_length=10, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('pic', models.CharField(max_length=15, null=True)),
                ('civil_state', models.CharField(max_length=15, null=True)),
                ('nationality', models.CharField(max_length=15, null=True)),
                ('id_card_number', models.CharField(max_length=15, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25, null=True)),
                ('county', models.CharField(max_length=15, null=True)),
                ('locality', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=25, null=True)),
                ('street_number', models.CharField(max_length=8, null=True)),
                ('block', models.CharField(max_length=5, null=True)),
                ('stair', models.CharField(max_length=5, null=True)),
                ('floor', models.CharField(max_length=5, null=True)),
                ('apartament', models.CharField(max_length=5, null=True)),
                ('rural', models.BooleanField()),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacalaureat_diploma', models.CharField(max_length=100, null=True)),
                ('diploma_equivalent', models.CharField(max_length=100, null=True)),
                ('id_card', models.CharField(max_length=100, null=True)),
                ('birth_certificate', models.CharField(max_length=100, null=True)),
                ('student_photo', models.CharField(max_length=100, null=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Aditional_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacalaureat_diploma', models.CharField(max_length=100, null=True)),
                ('diploma_equivalent', models.CharField(max_length=100, null=True)),
                ('id_card', models.CharField(max_length=100, null=True)),
                ('birth_certificate', models.CharField(max_length=100, null=True)),
                ('student_photo', models.CharField(max_length=100, null=True)),
                ('document_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.documents')),
            ],
        ),
    ]
