# Generated by Django 3.1.3 on 2020-11-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('nume', models.CharField(max_length=25)),
                ('descriere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=15)),
                ('locality', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=25)),
                ('street_number', models.CharField(max_length=8)),
                ('block', models.CharField(max_length=5)),
                ('staircase', models.CharField(max_length=5)),
                ('floor', models.CharField(max_length=5)),
                ('apartament', models.CharField(max_length=5)),
                ('rural', models.BooleanField()),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('diploma', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=100)),
                ('faculty_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
    ]
