# Generated by Django 3.1.3 on 2020-11-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201115_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='token',
            name='username_id',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
