# Generated by Django 3.1.3 on 2020-11-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20201115_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=25)),
                ('descriere', models.CharField(max_length=100)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('username_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=15)),
                ('locality', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=25)),
                ('street_number', models.CharField(max_length=8)),
                ('block', models.CharField(max_length=5)),
                ('staircase', models.CharField(max_length=5)),
                ('floor', models.CharField(max_length=5)),
                ('apartament', models.CharField(max_length=5)),
                ('rural', models.BooleanField()),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('diploma', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=100)),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
