# Generated by Django 3.1.3 on 2020-11-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201115_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='username_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
