# Generated by Django 3.1.3 on 2020-11-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201115_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='username_id',
        ),
        migrations.AddField(
            model_name='token',
            name='username',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
            preserve_default=False,
        ),
    ]
