# Generated by Django 3.1.3 on 2020-11-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201115_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditional_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacalaureat_diploma', models.CharField(max_length=100, null=True)),
                ('diploma_equivalent', models.CharField(max_length=100, null=True)),
                ('id_card', models.CharField(max_length=100, null=True)),
                ('birth_certificate', models.CharField(max_length=100, null=True)),
                ('student_photo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacalaureat_diploma', models.CharField(max_length=100, null=True)),
                ('diploma_equivalent', models.CharField(max_length=100, null=True)),
                ('id_card', models.CharField(max_length=100, null=True)),
                ('birth_certificate', models.CharField(max_length=100, null=True)),
                ('student_photo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25, null=True)),
                ('county', models.CharField(max_length=15, null=True)),
                ('locality', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=25, null=True)),
                ('street_number', models.CharField(max_length=8, null=True)),
                ('block', models.CharField(max_length=5, null=True)),
                ('stair', models.CharField(max_length=5, null=True)),
                ('floor', models.CharField(max_length=5, null=True)),
                ('apartament', models.CharField(max_length=5, null=True)),
                ('rural', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='section',
            name='descriere',
        ),
        migrations.RemoveField(
            model_name='section',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='student',
            name='apartament',
        ),
        migrations.RemoveField(
            model_name='student',
            name='block',
        ),
        migrations.RemoveField(
            model_name='student',
            name='county',
        ),
        migrations.RemoveField(
            model_name='student',
            name='diploma',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='student',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rural',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='staircase',
        ),
        migrations.RemoveField(
            model_name='student',
            name='street',
        ),
        migrations.RemoveField(
            model_name='student',
            name='street_number',
        ),
        migrations.AddField(
            model_name='faculty',
            name='logo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='faculta_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty'),
        ),
        migrations.AddField(
            model_name='section',
            name='logo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='civil_state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='student_faculty',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.faculty'),
        ),
        migrations.AddField(
            model_name='student_faculty',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section'),
        ),
        migrations.AddField(
            model_name='student_faculty',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AddField(
            model_name='location',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AddField(
            model_name='documents',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AddField(
            model_name='aditional_documents',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.documents'),
        ),
    ]
